=== jsuasnavas5334/RHIA/packages/contracts/generated/json-schema/ApprovalDecision.schema.json
{
  "$id": "https://schemas.rhia.invalid/v1/ApprovalDecision.schema.json",
  "title": "RHIA ApprovalDecision v1",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "string",
      "const": "1.0"
    },
    "approvalId": {
      "type": "string",
      "format": "uuid",
      "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
    },
    "correlationId": {
      "type": "string",
      "format": "uuid",
      "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
    },
    "decision": {
      "type": "string",
      "enum": [
        "APPROVED",
        "REJECTED",
        "EXPIRED"
      ]
    },
    "decidedAt": {
      "type": "string",
      "format": "date-time",
      "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$"
    },
    "decidedByRef": {
      "type": "string",
      "format": "uuid",
      "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
    },
    "reason": {
      "type": "string",
      "maxLength": 1000
    }
  },
  "required": [
    "version",
    "approvalId",
    "correlationId",
    "decision",
    "decidedAt",
    "decidedByRef"
  ],
  "additionalProperties": false
}

=== jsuasnavas5334/RHIA/packages/contracts/examples/approval-decision.json
{
  "version": "1.0",
  "approvalId": "77777777-7777-4777-8777-777777777777",
  "correlationId": "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  "decision": "REJECTED",
  "decidedAt": "2026-08-20T20:05:00Z",
  "decidedByRef": "12121212-1212-4121-8121-121212121212",
  "reason": "La condición comercial no fue autorizada."
}
